httpTimeout: 600000

nmHoistingLimits: none

nodeLinker: pnpm

packageExtensions:
  "@bull-board/api@*":
    peerDependencies:
      "@bull-board/ui": "*"
  "@vitejs/plugin-vue@*":
    dependencies:
      supports-color: "*"
  chartjs-adapter-date-fns@*:
    peerDependencies:
      date-fns: "*"
  consolidate@*:
    dependencies:
      ejs: "*"
  koa-views@*:
    dependencies:
      pug: "*"
  swiper@*:
    peerDependencies:
      vue: "*"
  vite@*:
    dependencies:
      bufferutil: "*"
      supports-color: "*"
      utf-8-validate: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.3.1.cjs
