apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iceshrimp.fullname" . }}-config
  labels:
    {{- include "iceshrimp.labels" . | nindent 4 }}
type: Opaque
data:
  default.yml: {{ include "iceshrimp.configDir.default.yml" . | b64enc }}
