pipeline:
  docker-build:
    image: plugins/kaniko
    settings:
      repo: thatonecalculator/calckey
      tags: test
      dockerfile: Dockerfile
      no_push: true

branches:
  include: [ main, develop ]
