pipeline:
  docker-build:
    image: plugins/kaniko
    settings:
      repo: iceshrimp/iceshrimp
      tags: test
      dockerfile: Dockerfile
      no_push: true

branches:
  include: [ main, develop, beta ]
